version: 2

updates:
  # npm == yarn in dependabot
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: "sunday"
    groups:
      npm-dependencies:
        patterns:
          - "*" # Include all dependencies in one PR
        update-types:
          - "minor"
          - "patch"

    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
  - package-ecosystem: gomod
    directory: .sage
    schedule:
      interval: monthly
      day: "sunday"
    groups:
      go-dependencies:
        patterns:
          - "*" # Include all dependencies in one PR
        update-types:
          - "minor"
          - "patch"
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
