version: 2

updates:
  # npm == yarn in dependabot
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: "sunday"
    groups:
      npm-dependencies:
        patterns:
          - "*" # Include all dependencies in one PR
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: gomod
    directory: .sage
    schedule:
      interval: monthly
      day: "sunday"
    groups:
      go-dependencies:
        patterns:
          - "*" # Include all dependencies in one PR
        update-types:
          - "minor"
          - "patch"
