yarnPath: .yarn/releases/yarn-3.5.0.cjs
defaultSemverRangePrefix: ""
nodeLinker: node-modules

npmScopes:
  saga:
    npmAlwaysAuth: true
    npmRegistryServer: "https://europe-west1-npm.pkg.dev/e-npm-registry-prod/npm/"
